'use client'
import { useState } from 'react'
import { requestJson } from '@/lib/ps/client'
type Data = { mode: 'individual' | 'pair'; targets: { id: string; label: string }[]; assignments: { id: string; name: string; grader_email: string }[] }
export default function PSReassignment({ roundId, readOnly = false }: { roundId: string; readOnly?: boolean }) {
  const [data, setData] = useState<Data | null>(null), [assignment, setAssignment] = useState(''), [target, setTarget] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  async function run(transfer: boolean) { setBusy(true); setMessage(''); try { if (transfer) await requestJson(`/api/ps/rounds/${roundId}/reassign`, { assignment_id: assignment, target_email: target }); setData(await requestJson<Data>(`/api/ps/rounds/${roundId}/reassign`)); setAssignment(''); setTarget(''); if (transfer) setMessage('Pending assignment transferred. Completed reviews remain unchanged.') } catch (e) { setMessage((e as Error).message) } finally { setBusy(false) } }
  const control = 'w-full border border-[var(--border)] bg-[var(--bg-raised)] rounded-lg px-3 py-2'
  return <details className="rounded-xl border border-[var(--border)] p-5 space-y-3"><summary className="font-semibold">Reassign pending work</summary>{readOnly && <p role="status" className="text-sm mt-3">Reassignment is available only during grading in an active cycle.</p>}<p className="text-sm mt-3">Transfer a pending assignment to another eligible grader. This can change the workload balance.</p><button disabled={busy} className="border border-[var(--border)] rounded-lg px-3 py-2" onClick={() => void run(false)}>Load pending assignments</button>{data && <><label className="block">Pending assignment<select className={control} value={assignment} onChange={e => setAssignment(e.target.value)}><option value="">Select assignment</option>{data.assignments.map(a => <option key={a.id} value={a.id}>{a.name} · {a.grader_email}</option>)}</select></label><label className="block">{data.mode === 'pair' ? 'Receiving pair' : 'Receiving grader'}<select className={control} value={target} onChange={e => setTarget(e.target.value)}><option value="">{data.mode === 'pair' ? 'Select a pair' : 'Select eligible grader'}</option>{data.targets.map(t => <option key={t.id} value={t.id}>{t.label}</option>)}</select></label><button disabled={busy || readOnly || !assignment || !target} className="border border-[var(--border)] rounded-lg px-3 py-2 disabled:opacity-40" onClick={() => void run(true)}>Transfer pending assignment</button></>}{message && <p role="status">{message}</p>}</details>
}
